name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        
    - name: Install Buildozer
      run: pip install buildozer cython==0.29.33
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: termux-clicker-apk
        path: bin/*.apk
