name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        buildozer-version: stable
        command: buildozer android debug
