name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip \
          openjdk-11-jdk \
          python3-pip python3-venv \
          autoconf libtool pkg-config \
          zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          cmake \
          libffi-dev libssl-dev \
          libsqlite3-dev \
          libjpeg-dev libtiff-dev libpng-dev
        
    - name: Install Buildozer
      run: pip install buildozer
        
    - name: Build APK with Buildozer
      run: |
        buildozer init
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: termux-clicker-apk
        path: bin/*.apk
        retention-days: 7
