name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-dev \
          openjdk-11-jdk \
          git zip unzip wget \
          build-essential \
          libffi-dev libssl-dev \
          libjpeg-dev libtiff-dev libpng-dev \
          autoconf libtool pkg-config \
          cmake ninja-build
        
    - name: Install Python packages
      run: |
        pip3 install buildozer
        pip3 install cython==0.29.33
        
    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
        
    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: termux-clicker-apk
        path: bin/*.apk
